= GR8 CRM - AWS Content Plugin
Göran Ehrsson <goran@technipelago.se>
:description: Official documentation for the GR8 CRM AWS Content Plugin
:keywords: groovy, grails, crm, gr8crm, aws, s3, documentation
:toc:
:numbered:
:icons: font
:imagesdir: ./images
:source-highlighter: prettify
:homepage: http://gr8crm.github.io
:gr8crm: GR8 CRM
:gr8source: https://github.com/technipelago/grails-crm-content-aws
:license: This plugin is licensed with http://www.apache.org/licenses/LICENSE-2.0.html[Apache License version 2.0]

== Introduction

{gr8crm} is a set of http://www.grails.org/[Grails Web Application Framework]
plugins that makes it easy to develop web applications with CRM functionality.

You can find more information about {gr8crm} on the main documentation site {homepage}.

=== Customer Relationship Management

Customer relationship management (CRM) is a system for managing a company’s interactions with current and future customers.
It involves using technology to organize, automate and synchronize sales, marketing, customer service, and technical support.
http://en.wikipedia.org/wiki/Customer_relationship_management[Wikipedia]

The {gr8crm} "Ecosystem" currently contains over 40 Grails plugins. For a complete list of plugins see {homepage}.

Each {gr8crm} plugin defines a http://martinfowler.com/bliki/BoundedContext.html[Bounded Context]
that focus on one specific domain, for example *contact*, *project* or *document*.

== AWS Content Plugin

This Grails plugin extends the https://github.com/technipelago/grails-crm-content[crm-content] plugin to store all content in Amazon S3 buckets
instead of in the local server file system.

This plugin adds a `AwsContentProvider` implementation that uses *AWS Java SDK* for object storage.
All standard GR8 CRM content management features works the same was as the default implementation
that stores object in local file system.

== Installation

Declare the plugin dependency in the `BuildConfig.groovy` file, as shown here:

[source,groovy,subs="attributes"]
----
grails.project.dependency.resolution = {
    inherits "global"
    log "info"
    repositories {
        // your repositories
    }
    dependencies {
        // Workaround to resolve dependency issue with aws-java-sdk and http-builder (dependent on httpcore:4.0)
        build 'org.apache.httpcomponents:httpcore:4.4.5'
        build 'org.apache.httpcomponents:httpclient:4.5.2'
        runtime 'org.apache.httpcomponents:httpcore:4.4.5'
        runtime 'org.apache.httpcomponents:httpclient:4.5.2'
    }
    plugins {
        // here go your plugin dependencies
        runtime ':crm-content-aws:{revnumber}'
    }
}
----

== Configuration

This plugin uses the same configuration parameters as the https://grails.org/plugin/aws-sdk[aws-sdk] plugin.

----
    grails.plugin.awssdk.endpoint = 'https://s3.us-east-1.amazonaws.com' <1>
    grails.plugin.awssdk.accessKey = '<aws key>'
    grails.plugin.awssdk.secretKey = '<aws secret>'
    grails.plugin.awssdk.region = 'us-east-1'
----
<1> List of https://docs.aws.amazon.com/general/latest/gr/rande.html#s3_region[AWS S3 Regions]

Currently all GR8 CRM content are stored in the same bucket, configured with:

    crm.content.s3.bucket = '<bucket name>' // default 'grails'

== Extensions

You can write business logic that decides what content provider to use.
You do this by replacing the bean named `crmContentRouter` with an implementation
that can use *content name*, *content length*, *domain instance* that the content is attached to,
or the *current user* to decide what content provider to route to.

The following example route all images to Amazon S3 and all other content
to the default `crmFileContentProvider` that store files in the local file system.

[source,groovy]
.src/groovy/my/package/ImageContentRouter.groovy
----
package my.package

import grails.plugins.crm.content.CrmContentProvider
import grails.plugins.crm.content.CrmContentRouter

/**
 * Route all images to Amazon S3.
 */
class ImageContentRouter implements CrmContentRouter {

    def crmFileContentProvider
    def awsContentProvider

    @Override
    CrmContentProvider getProvider(String filename, long length, Object reference, String username) {
        isImage(filename) ? awsContentProvider : crmFileContentProvider
    }

    private boolean isImage(String filename) {
        for (ext in [".png", ".jpg", ".jpeg", ".gif"]) {
            if (filename.toLowerCase().endsWith(ext)) {
                return true
            }
        }
        return false
    }
}
----

[source,groovy]
.grails-app/conf/spring/resources.groovy
----
beans = {
    crmContentRouter(my.package.ImageContentRouter) { bean ->
        bean.autowire = 'byName'
    }
}
----

== Changes

2.4.3:: Use `aws-java-sdk-s3` directly instead of the aws-sdk plugin (to make it easier to use minio.io)
2.4.2:: Make sure S3Object is closed after use. Adds method withObjects(Closure).
2.4.1:: First public release


== License

{license}

== Source Code

The source code for this plugin is available at {gr8source}

== Contributing

Please report {gr8source}/issues[issues or suggestions].

Want to improve the plugin: Fork the {gr8source}[repository] and send a pull request.
