= GR8 CRM - AWS Content Plugin
Göran Ehrsson <goran@technipelago.se>
:description: Official documentation for the GR8 CRM AWS Content Plugin
:keywords: groovy, grails, crm, gr8crm, aws, s3, documentation
:toc:
:numbered:
:icons: font
:imagesdir: ./images
:source-highlighter: prettify
:homepage: http://gr8crm.github.io
:gr8crm: GR8 CRM
:gr8source: https://github.com/technipelago/grails-crm-content-aws
:license: This plugin is licensed with http://www.apache.org/licenses/LICENSE-2.0.html[Apache License version 2.0]

== Introduction

{gr8crm} is a set of http://www.grails.org/[Grails Web Application Framework]
plugins that makes it easy to develop web applications with CRM functionality.

You can find more information about {gr8crm} on the main documentation site {homepage}.

=== Customer Relationship Management

Customer relationship management (CRM) is a system for managing a company’s interactions with current and future customers.
It involves using technology to organize, automate and synchronize sales, marketing, customer service, and technical support.
http://en.wikipedia.org/wiki/Customer_relationship_management[Wikipedia]

The {gr8crm} "Ecosystem" currently contains over 40 Grails plugins. For a complete list of plugins see {homepage}.

Each {gr8crm} plugin defines a http://martinfowler.com/bliki/BoundedContext.html[Bounded Context]
that focus on one specific domain, for example *contact*, *project* or *document*.

== AWS Content Plugin

This Grails plugin extends the https://github.com/technipelago/grails-crm-content[crm-content] plugin to store all content in Amazon S3 buckets
instead of in the local server file system.

This plugin is quite thin thanks to two great plugins, https://grails.org/plugin/aws-sdk[aws-sdk],
and https://github.com/technipelago/grails-crm-content[crm-content].
The AWS plugin makes it easy to store objects in Amazon S3 and the crm-content plugin has
support for "content providers". So this plugin just adds the `AwsContentProvder`
implementation that leverages *aws-sdk* for object storage. All standard GR8 CRM content
management features works the same was as the default implementation that stores object
in local file system.

== Installation

Declare the plugin dependency in the `BuildConfig.groovy` file, as shown here:

[source,groovy,subs="attributes"]
----
grails.project.dependency.resolution = {
    inherits "global"
    log "info"
    repositories {
        // your repositories
    }
    dependencies {
        // Workaround to resolve dependency issue with aws-java-sdk and http-builder (dependent on httpcore:4.0)
        build 'org.apache.httpcomponents:httpcore:4.4.5'
        build 'org.apache.httpcomponents:httpclient:4.5.2'
        runtime 'org.apache.httpcomponents:httpcore:4.4.5'
        runtime 'org.apache.httpcomponents:httpclient:4.5.2'
    }
    plugins {
        // here go your plugin dependencies
        runtime ':crm-content-aws:{revnumber}'
    }
}
----

== Configuration

This plugin uses the excellent https://grails.org/plugin/aws-sdk[aws-sdk] plugin
to communicate with Amazon S3, so all configuration options for *aws-sdk* apply.

    grails.plugin.awssdk.accessKey = '<aws key>'
    grails.plugin.awssdk.secretKey = '<aws secret>'
    grails.plugin.awssdk.region = '<aws region>'

Currently all GR8 CRM content are stored in the same bucket, configured with:

    crm.content.s3.bucket = '<bucket name>' // default 'grails'

== Changes

2.4.0:: First public release

== Roadmap

The current (2.4.0) implementation overrides the default `ContentProviderFactory` with
`AwsContentProviderFactory` that always returns an `AwsContentProvider` instance.
This means that *all* content in the same Grails application will be stored in Amazon S3.
It would be nice to be able to store some content in S3, some in local file system and
(in the future) some content elsewhere depending on business logic.

Some kind of generic `ContentProviderFactory` is needed that knows about all
`ContentProvider` implementations avaiable in the application. Then business logic
would assign a content provider that is most suitable for the type of content read/written.

== License

{license}

== Source Code

The source code for this plugin is available at {gr8source}

== Contributing

Please report {gr8source}/issues[issues or suggestions].

Want to improve the plugin: Fork the {gr8source}[repository] and send a pull request.
