= GR8 CRM AWS Content Plugin

This Grails plugin extends the https://github.com/technipelago/grails-crm-content[crm-content] plugin to store all content in Amazon S3 buckets
instead of in the local server file system.

This plugin is quite thin thanks to two great plugins, https://grails.org/plugin/aws-sdk[aws-sdk],
and https://github.com/technipelago/grails-crm-content[crm-content].
The AWS plugin makes it easy to store objects in Amazon S3 and the crm-content plugin has
support for "content providers". So this plugin just adds the `AwsContentProvder`
implementation that leverages *aws-sdk* for object storage. All standard GR8 CRM content
management features works the same was as the default implementation that stores object
in local file system.

== Configuration

This plugin uses the excellent https://grails.org/plugin/aws-sdk[aws-sdk] plugin
to communicate with Amazon S3, so all configuration options for *aws-sdk* apply.

    grails.plugin.awssdk.accessKey = '<aws key>'
    grails.plugin.awssdk.secretKey = '<aws secret>'
    grails.plugin.awssdk.region = '<aws region>'

Currently all GR8 CRM content are stored in the same bucket, configured with:

    crm.content.s3.bucket = '<bucket name>' // default 'grails'


== Documentation

Complete documentation for this plugin can be found at http://gr8crm.github.io/plugins/crm-content-aws/[gr8crm.github.io]
